#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-compress-lzf
Version  : 1.0.3
Release  : 1
URL      : https://repo1.maven.org/maven2/com/ning/compress-lzf/1.0.3/compress-lzf-1.0.3.jar
Source0  : https://repo1.maven.org/maven2/com/ning/compress-lzf/1.0.3/compress-lzf-1.0.3.jar
Source1  : https://repo1.maven.org/maven2/com/ning/compress-lzf/1.0.3/compress-lzf-1.0.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-compress-lzf-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-compress-lzf package.
Group: Data

%description data
data components for the mvn-compress-lzf package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/ning/compress-lzf/1.0.3
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/com/ning/compress-lzf/1.0.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/ning/compress-lzf/1.0.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/ning/compress-lzf/1.0.3


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/ning/compress-lzf/1.0.3/compress-lzf-1.0.3.jar
/usr/share/java/.m2/repository/com/ning/compress-lzf/1.0.3/compress-lzf-1.0.3.pom
